config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'books#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top

  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end



 def create
    @book = Book.new(book_params)
    if @book.save
       redirect_to book_path(@book),flash: {notice: 'Book was successfully created.'}
    else
      @books=Book.all
      render :index
    end

 end

 def destroy
    book = Book.find(params[:id])
    if book.destroy
       redirect_to books_path,flash: {notice: 'Book was successfully destroyed.'}
    else
       render :index
    end
 end

 def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book),flash: {notice: 'Book was successfully updated.'}
    else
      render :show
    end
 end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, local:true do |f| %>

<div class="field">
  <lavel for="book_title">Title</lavel>
  <%= f.text_field :title %>
</div>

<div class="field">
  <lavel for="book_body">Body</lavel>
  <%= f.text_area :body %>
</div>

<div class="actions">
  <%= f.submit 'Update Book' %>
</div>

<% end %>

<span>
        <%= link_to "Show",book_path(@book.id) %>
        |
        <%= link_to "Back",books_path %>
</span>

app/views/books/index.html.erb
<% if flash[:notice] %>
   <%= flash[:notice] %>
<% end %>

<h1>Books</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th colspan=3></th>
      </tr>
    </thead>

    <tbody>

      <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id) %></td>
        <td><%= link_to "Edit", edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy", book_path(book.id), method: :delete ,"data-confirm"=>"Are you sure?" %></td>
      </tr>
      <% end %>
    </tbody>


  </table>


<h2>New Book</h2>

<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2>
        <%= pluralize(@book.errors.count, "error") %>
        prohibited this book from being saved:
    </h2>

    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- form_with部分 -->
<%= form_with model:@book, local:true do |f| %>

<div class="field">
  <lavel for="book_title">Title</lavel>
  <%= f.text_field :title %>
</div>

<div class="field">
  <lavel for="book_body">Body</lavel>
  <%= f.text_area :body %>
</div>

<div class="actions">
  <%= f.submit 'Create Book' %>
</div>

<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
   <%= flash[:notice] %>
<% end %>

<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2>
        <%= pluralize(@book.errors.count, "error") %>
        prohibited this book from being saved:
    </h2>

    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <Strong>Title:</Strong>
  <%= @book.title %>
</p>

<p>
  <Strong>Body:</Strong>
  <%= @book.body %>
</p>

 <span>
        <%= link_to "Edit",edit_book_path(@book.id) %>
        |
        <%= link_to "Back",books_path %>
</span>

app/views/books/top.html.erb
<!--body-->
<body>
    <h1>
        ようこそ<strong>Bookers</strong>へ！
    </h1>

    <p>
        <strong>Bookers</strong>
        では、さまざまな書籍に関するあなたの意見や
    </p>

    <p>印象を共有し交換することができます</p>

    <span>
        <%= link_to "start", books_path %>
    </span>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>